module_order:
  - fastqc:
      name: "FastQC (raw)"
      anchor: "fastqc_raw"
      path_filters:
        - "01_qc/fastqc_pre/*_fastqc.zip"
  - fastp:
    path_filters:
        - "01_qc/fastp/*.json"
  - fastqc:
      name: "FastQC (Fastp)"
      anchor: "fastqc_trimmed"
      info: "This section of the report shows FastQC results after fastp."
      target: ""
      path_filters:
        - "01_qc/fastqc_fastp/*_fastqc.zip"
  - bowtie2

exclude_modules:
  - featureCounts
  - sortmerna